"""Create alignment_queue table

Revision ID: 001
Revises: 
Create Date: 2025-08-03 18:52:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alignment_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=500), nullable=False),
    sa.Column('text_file_path', sa.String(length=500), nullable=False),
    sa.Column('original_audio_filename', sa.String(length=255), nullable=False),
    sa.Column('original_text_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='alignmentstatus'), nullable=False),
    sa.Column('result_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alignment_queue_id'), 'alignment_queue', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alignment_queue_id'), table_name='alignment_queue')
    op.drop_table('alignment_queue')
    # ### end Alembic commands ###
